<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teams= [
            [
                'name' => "Barcelona",
                'stadium' => "Camp Nou",
                'foundation_year' => 1899,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/3.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Sevilla",
                'stadium' => "Ramón Sánchez-Pizjuán",
                'foundation_year' => 1890,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/53.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Real Sociedad",
                'stadium' => "Anoeta",
                'foundation_year' => 1909,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/16.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Real Madrid",
                'stadium' => "Bernabéu",
                'foundation_year' => 1902,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/1.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Atlético de Madrid",
                'stadium' => "Metropolitano",
                'foundation_year' => 1903,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/42.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Real Betis",
                'stadium' => "Benito Villamarín",
                'foundation_year' => 1907,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/171.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Villarreal",
                'stadium' => "Estadio de la Cerámica",
                'foundation_year' => 1923,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/19.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Athletic Club de Bilbao",
                'stadium' => "San Mamés",
                'foundation_year' => 1898,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/5.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Valencia",
                'stadium' => "Mestalla",
                'foundation_year' => 1919,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/17.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Osasuna",
                'stadium' => "El Sadar",
                'foundation_year' => 1920,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/13.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Celta de Vigo",
                'stadium' => "Balaídos",
                'foundation_year' => 1923,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/6.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Rayo Vallecano",
                'stadium' => "Vallecas",
                'foundation_year' => 1924,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/2.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Getafe",
                'stadium' => "Coliseum Alfonso Pérez",
                'foundation_year' => 1983,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/172.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Mallorca",
                'stadium' => "Visit Mallorca Stadium",
                'foundation_year' => 1916,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/11.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Cádiz",
                'stadium' => "Nuevo Mirandilla",
                'foundation_year' => 1910,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/91.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Almería",
                'stadium' => "Power Horse Stadium",
                'foundation_year' => 1989,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/85.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Girona",
                'stadium' => "Montilivi",
                'foundation_year' => 1930,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/648.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Alavés",
                'stadium' => "Mendizorroza",
                'foundation_year' => 1921,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/4.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Granada",
                'stadium' => "Nuevo Los Cármenes",
                'foundation_year' => 1931,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/347.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Las Palmas",
                'stadium' => "Gran Canaria",
                'foundation_year' => 1949,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/9.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Elche",
                'stadium' => "Manuel Martínez Valero",
                'foundation_year' => 1923,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/121.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Español",
                'stadium' => "Cornellà-El Prat",
                'foundation_year' => 1900,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/8.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
            [
                'name'=> "Valladolid",
                'stadium' => "José Zorrilla",
                'foundation_year' => 1928,
                'emblem_photo'=> "https://as01.epimg.net/img/comunes/fotos/fichas/equipos/large/18.png",
                'points' => 0,
                'num_games' => 0,
                'won' => 0,
                'draw' => 0,
                'lost' => 0,
                'goals' => 0,
                'against' => 0,
                'average' => 0,
            ],
        ];

        foreach ($teams as $teamData) {
            Team::create($teamData);
        }
    }
}
